# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'
use_frameworks!

target 'FocusON' do
    pod 'SwiftCharts', '~> 0.6.5'
end

target 'FocusONTests' do
    pod 'SwiftCharts', '~> 0.6.5'
end
